### PR TITLE
A functional Cozy

### PR DESCRIPTION
**Pull request by nledez**

### CODE REVIEW

**Comment by moul** [comment]
Thank you @nledez 

@QuentinPerez can you give a look ?

**Comment by QuentinPerez** [comment]
LGTM maybe we will use `update-motd` instead of welcome message into the `bashrc` file

**Comment by moul** [comment]
Yep, I merge this functional cozy, then we can propose improvements :)

**Comment by moul** [comment]
The image is now building: https://travis-ci.org/scaleway/qa/builds/94886653

**Pull request merged**
